# generated by datamodel-codegen:
#   filename:  https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v2.0.json
#   timestamp: 2023-06-22T21:17:26+00:00
from __future__ import annotations

from enum import Enum

from pydantic import BaseModel
from pydantic import ConstrainedFloat
from pydantic import ConstrainedStr
from pydantic import Field


class Vector(ConstrainedStr):
    regex = r"^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"


class Version(Enum):
    field_2_0 = "2.0"


class AccessVectorType(Enum):
    NETWORK = "NETWORK"
    ADJACENT_NETWORK = "ADJACENT_NETWORK"
    LOCAL = "LOCAL"


class AccessComplexityType(Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AuthenticationType(Enum):
    MULTIPLE = "MULTIPLE"
    SINGLE = "SINGLE"
    NONE = "NONE"


class CiaType(Enum):
    NONE = "NONE"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"


class ExploitabilityType(Enum):
    UNPROVEN = "UNPROVEN"
    PROOF_OF_CONCEPT = "PROOF_OF_CONCEPT"
    FUNCTIONAL = "FUNCTIONAL"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class RemediationLevelType(Enum):
    OFFICIAL_FIX = "OFFICIAL_FIX"
    TEMPORARY_FIX = "TEMPORARY_FIX"
    WORKAROUND = "WORKAROUND"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_DEFINED = "NOT_DEFINED"


class ReportConfidenceType(Enum):
    UNCONFIRMED = "UNCONFIRMED"
    UNCORROBORATED = "UNCORROBORATED"
    CONFIRMED = "CONFIRMED"
    NOT_DEFINED = "NOT_DEFINED"


class CollateralDamagePotentialType(Enum):
    NONE = "NONE"
    LOW = "LOW"
    LOW_MEDIUM = "LOW_MEDIUM"
    MEDIUM_HIGH = "MEDIUM_HIGH"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class TargetDistributionType(Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class CiaRequirementType(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class ScoreType(ConstrainedFloat):
    ge = 0.0
    le = 10.0


class CVSS20(BaseModel):
    version: Version = Field(..., description="CVSS Version")
    vectorString: Vector
    accessVector: AccessVectorType | None = None
    accessComplexity: AccessComplexityType | None = None
    authentication: AuthenticationType | None = None
    confidentialityImpact: CiaType | None = None
    integrityImpact: CiaType | None = None
    availabilityImpact: CiaType | None = None
    baseScore: ScoreType
    exploitability: ExploitabilityType | None = None
    remediationLevel: RemediationLevelType | None = None
    reportConfidence: ReportConfidenceType | None = None
    temporalScore: ScoreType | None = None
    collateralDamagePotential: CollateralDamagePotentialType | None = None
    targetDistribution: TargetDistributionType | None = None
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    environmentalScore: ScoreType | None = None
