# generated by datamodel-codegen:
#   filename:  cvss-v3.0.json
#   timestamp: 2023-07-25T18:42:41+00:00
from __future__ import annotations

from enum import Enum

from pydantic import BaseModel
from pydantic import Field
from pydantic import RootModel


class Version(Enum):
    field_3_0 = "3.0"


class AttackVectorType(Enum):
    NETWORK = "NETWORK"
    ADJACENT_NETWORK = "ADJACENT_NETWORK"
    LOCAL = "LOCAL"
    PHYSICAL = "PHYSICAL"


class ModifiedAttackVectorType(Enum):
    NETWORK = "NETWORK"
    ADJACENT_NETWORK = "ADJACENT_NETWORK"
    LOCAL = "LOCAL"
    PHYSICAL = "PHYSICAL"
    NOT_DEFINED = "NOT_DEFINED"


class AttackComplexityType(Enum):
    HIGH = "HIGH"
    LOW = "LOW"


class ModifiedAttackComplexityType(Enum):
    HIGH = "HIGH"
    LOW = "LOW"
    NOT_DEFINED = "NOT_DEFINED"


class PrivilegesRequiredType(Enum):
    HIGH = "HIGH"
    LOW = "LOW"
    NONE = "NONE"


class ModifiedPrivilegesRequiredType(Enum):
    HIGH = "HIGH"
    LOW = "LOW"
    NONE = "NONE"
    NOT_DEFINED = "NOT_DEFINED"


class UserInteractionType(Enum):
    NONE = "NONE"
    REQUIRED = "REQUIRED"


class ModifiedUserInteractionType(Enum):
    NONE = "NONE"
    REQUIRED = "REQUIRED"
    NOT_DEFINED = "NOT_DEFINED"


class ScopeType(Enum):
    UNCHANGED = "UNCHANGED"
    CHANGED = "CHANGED"


class ModifiedScopeType(Enum):
    UNCHANGED = "UNCHANGED"
    CHANGED = "CHANGED"
    NOT_DEFINED = "NOT_DEFINED"


class CiaType(Enum):
    NONE = "NONE"
    LOW = "LOW"
    HIGH = "HIGH"


class ModifiedCiaType(Enum):
    NONE = "NONE"
    LOW = "LOW"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class ExploitCodeMaturityType(Enum):
    UNPROVEN = "UNPROVEN"
    PROOF_OF_CONCEPT = "PROOF_OF_CONCEPT"
    FUNCTIONAL = "FUNCTIONAL"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class RemediationLevelType(Enum):
    OFFICIAL_FIX = "OFFICIAL_FIX"
    TEMPORARY_FIX = "TEMPORARY_FIX"
    WORKAROUND = "WORKAROUND"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_DEFINED = "NOT_DEFINED"


class ConfidenceType(Enum):
    UNKNOWN = "UNKNOWN"
    REASONABLE = "REASONABLE"
    CONFIRMED = "CONFIRMED"
    NOT_DEFINED = "NOT_DEFINED"


class CiaRequirementType(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    NOT_DEFINED = "NOT_DEFINED"


class ScoreType(RootModel):  # type: ignore[type-arg]
    root: float = Field(..., ge=0.0, le=10.0)


class SeverityType(Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CVSS30(BaseModel):
    version: Version = Field(..., description="CVSS Version")
    vectorString: str = Field(
        ...,
        pattern="^CVSS:3[.]0/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$",
    )
    attackVector: AttackVectorType | None = None
    attackComplexity: AttackComplexityType | None = None
    privilegesRequired: PrivilegesRequiredType | None = None
    userInteraction: UserInteractionType | None = None
    scope: ScopeType | None = None
    confidentialityImpact: CiaType | None = None
    integrityImpact: CiaType | None = None
    availabilityImpact: CiaType | None = None
    baseScore: ScoreType
    baseSeverity: SeverityType
    exploitCodeMaturity: ExploitCodeMaturityType | None = None
    remediationLevel: RemediationLevelType | None = None
    reportConfidence: ConfidenceType | None = None
    temporalScore: ScoreType | None = None
    temporalSeverity: SeverityType | None = None
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    modifiedAttackVector: ModifiedAttackVectorType | None = None
    modifiedAttackComplexity: ModifiedAttackComplexityType | None = None
    modifiedPrivilegesRequired: ModifiedPrivilegesRequiredType | None = None
    modifiedUserInteraction: ModifiedUserInteractionType | None = None
    modifiedScope: ModifiedScopeType | None = None
    modifiedConfidentialityImpact: ModifiedCiaType | None = None
    modifiedIntegrityImpact: ModifiedCiaType | None = None
    modifiedAvailabilityImpact: ModifiedCiaType | None = None
    environmentalScore: ScoreType | None = None
    environmentalSeverity: SeverityType | None = None
